version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/container
    depends_on:
      - db

  ui:
    build:
      context: ./ui
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app/container
      - /app/container/src/node_modules
    depends_on:
      - api

  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
