# Generated by Django 4.2.2 on 2023-09-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_expensegroup_name_expensegroup_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='totalPrice',
            new_name='total',
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='expensegroup',
            name='value',
            field=models.CharField(default='', max_length=255, verbose_name='Значение'),
        ),
    ]
